# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: inf6c/php:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
          - ./vendor
          key: dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: vendor/bin/phpunit
  deploy_dev:
    docker:
      - image: coxauto/aws-ebcli:latest

    working_directory: ~/repo
    steps:
      - checkout
      - run: echo $COMPOSER_AUTH >> auth.json
      - run: echo N | eb init
      - run: eb deploy slipper-dev
  deploy_prod:
    docker:
    - image: coxauto/aws-ebcli:latest

    working_directory: ~/repo
    steps:
    - checkout
    - run: echo $COMPOSER_AUTH >> auth.json
    - run: echo N | eb init
    - run: eb deploy slipper-prod

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              ignore: master
      - deploy_prod:
          requires:
          - test
          filters:
            branches:
              only: master